---
layout: post
title: "Promise"
date: 2018-1-22
description: "Promise"
tag: js
comments: true
---

### Promise 对象

promise 对象javascript 异步解决方案，为异步操作提供统一接口，起到代理的作用，充当异步操作与回调函数之间的中介，使得异步操作具备同步操作接口，promise可以让异步操作写起来就像同步操作的流程，而不必一层层的嵌套回调函数

Promise 的设计思想是，所有异步任务都返回一个 Promise 实例。Promise 实例有一个then方法，用来指定下一步的回调函数。

    var p1 = new Promise(f1);
    p1.then(f2);

上面代码中，f1的异步操作执行完成，就会执行f2。

传统的写法可能需要把f2作为回调函数传入f1，比如写成f1(f2)，异步操作完成后，在f1内部调用f2。Promise 使得f1和f2变成了链式写法。不仅改善了可读性，而且对于多层嵌套的回调函数尤其方便。

    // 传统写法
    step1(function (value1) {
        step2(value1, function(value2) {
            step3(value2, function(value3) {
                step4(value3, function(value4) {
                    // ...
                });
            });
        });
    });

    // Promise 的写法
    (new Promise(step1))
    .then(step2)
    .then(step3)
    .then(step4);

一个 Promise 就是一个代表了异步操作最终完成或者失败的对象.  一个promise可以使用它的constructor创建。然而，大多数人都在使用由其他函数创建并返回的promise。因此，本教程将首先探讨返回promise的使用情况。

本质上，一个promise是某个函数返回的对象，你可以把回调函数绑定在这个对象上，而不是把回调函数当作参数传进函数。 

比如，promise替代了下面这种旧式的函数，这种旧式函数需要两个回调函数，并最终调用处理成功事件或者处理失败事件的回调函数：

    function successCallback(result) {
    console.log("It succeeded with " + result);
    }

    function failureCallback(error) {
    console.log("It failed with " + error);
    }

    doSomething(successCallback, failureCallback);

...新式函数返回一个你可以直接绑定回调函数的promise对象，来代替旧式的函数形式：

    let promise = doSomething(); 
    promise.then(successCallback, failureCallback);

…或者更简单的形式：

`doSomething().then(successCallback, failureCallback);`

我们把这个称为异步函数调用，这种形式有若干优点。我们将会逐一讨论。


### Promise的原理分析

#### Promise 对象的状态
Promise 对象通过自身的状态，来控制异步操作。Promise 实例具有三种状态。

- 异步操作未完成（pending）
- 异步操作成功（fulfilled）
- 异步操作失败（rejected）

上面三种状态里面，fulfilled和rejected合在一起称为resolved（已定型）。

#### Promise实例方法

Promise对象拥有两个实例方法then()和catch()。成功和失败的回调函数我们是通过then()添加，在promise状态改变时分别调用。promise构造函数中通常都是异步的，所以then方法往往都先于resolve和reject方法执行。所以promise内部需要有一个存储fulfill时调用函数的数组和一个存储reject时调用函数的数组。

then方法可以接收两个参数，且通常都是函数（非函数时如何处理下一篇文章中会详细介绍）。第一个参数会添加到fulfill时调用的数组中，第二个参数添加到reject时调用的数组中。当promise状态fulfill时，会把resolve(value)中的value值传给调用的函数中，同理，当promise状态reject时，会把reject(reason)中的reason值传给调用的函数。例：

then方法会返回一个新的promise，下面的例子中p == p1将返回false,说明p1是一个全新的对象。

    var p = new Promise(function(resolve, reject){
        resolve(5)
    })
    var p1 = p.then(function(value){
        console.log(value)
    })
    p == p1 // false

这也是为什么then是可以链式调用的，它是在新的对象上添加成功或失败的回调，这与jQuery中的链式调用不同。

那么新对象的状态是基于什么改变的呢？是不是说如果p的状态fulfill，后面的then创建的新对象都会成功；或者说如果p的状态reject，后面的then创建的新对象都会失败？

    var p = new Promise(function(resolve, reject){
        resolve(5)
    })
    var p1 = p.then(function(value){
        console.log(value)   // 5
    }).then(function(value){
        console.log('fulfill ' + value)   // fulfill undefined
    }, function(reason){
        console.log('reject ' + reason)   
    })

上面的例子会打印出5和"fulfill undefined"说明它的状态变为成功。那如果我们在p1的then方法中抛出异常呢？

    var p = new Promise(function(resolve, reject){
        resolve(5)
    })
    var p1 = p.then(function(value){
        console.log(value)   // 5
        throw new Error('test')
    }).then(function(value){
        console.log('fulfill ' + value)
    }, function(reason){
        console.log('reject ' + reason)   // reject Error: test
    })

理所当然，新对象肯定会失败。

反过来如果p失败了，会是什么样的呢？

    var p = new Promise(function(resolve, reject){
        reject(5)
    })
    var p1 = p.then(undefined, function(value){
        console.log(value)   // 5
    }).then(function(value){
        console.log('fulfill ' + value)   // fulfill undefined
    }, function(reason){
        console.log('reject ' + reason)
    })

说明新对象状态不会受到前一个对象状态的影响。

再来看如下代码：

    var p = new Promise(function(resolve, reject){
        reject(5)
    })
    var p1 = p.then(function(value){
        console.log(value) 
    })
    var p2 = p1.then(function(value){
        console.log('fulfill ' + value)
    }, function(reason){
        console.log('reject ' + reason)   // reject 5
    })

我们发现p1的状态变为rejected，从而触发了then方法第二个参数的函数。这似乎与我们之前提到的有差异啊，p1的状态受到了p的状态的影响。

再来看一个例子：

    var p = new Promise(function(resolve, reject){
        resolve(5)
    })
    var p1 = p.then(undefined, function(value){
        console.log(value) 
    })
    var p2 = p1.then(function(value){
        console.log('fulfill ' + value)   // fulfill 5
    }, function(reason){
        console.log('reject ' + reason)   
    })

细心的人可能会发现，该例子中then第一个参数是undefined，且value值5被传到了p1成功时的回调函数中。上面那个例子中then的第二个参数是undefined，同样reason值也传到了p1失败时的回调函数中。这是因当对应的参数不为函数时，会将前一promise的状态和值传递下去。

promise含有一个实例方法catch，从名字上我们就看得出来，它和异常有千丝万缕的关系。其实catch(onReject)方法等价于then(undefined, onReject)，也就是说如下两种情况是等效的。

    new Promise(function(resolve, reject){
        reject(new Error('error'))
    }).then(undefined, function(reason){
        console.log(reason) // Error: error(…)
    })

    new Promise(function(resolve, reject){
        reject(new Error('error'))
    }).catch(function(reason){
        console.log(reason) // Error: error(…)
    })

我们提到参数不为函数时会把值和状态传递下去。所以我们可以在多个then之后添加一个catch方法，这样前面只要reject或抛出异常，都会被最后的catch方法处理。

    new Promise(function(resolve, reject){
        resolve(5)
    }).then(function(value){
        taskA()
    }).then(function(value){
        taskB()
    }).then(function(value){
        taskC()
    }).catch(function(reason){
        console.log(reason)
    })

### Promise的静态方法

Promise还有四个静态方法，分别是resolve、reject、all、race

除了通过new Promise()的方式，我们还有两种创建Promise对象的方法：

- Promise.resolve() 它相当于创建了一个立即resolve的对象。如下两段代码作用相同：

    Promise.resolve(5)

    new Promise(function(resolve){
        resolve(5)
    })

它使得promise对象直接resolve，并把5传到后面then添加的成功函数中。

    Promise.resolve(5).then(function(value){
        console.log(value) // 5
    })

- Promise.reject() 很明显它相当于创建了一个立即reject的对象。如下两段代码作用相同：

    Promise.reject(new Error('error'))

    new Promise(function(resolve, reject){
        reject(new Error('error'))
    })

它使得promise对象直接reject，并把error传到后面catch添加的函数中。

    Promise.reject(new Error('error')).catch(function(reason){
        console.log(reason) // Error: error(…)
    })

- Promise.all() 它接收一个promise对象组成的数组作为参数，并返回一个新的promise对象。

当数组中所有的对象都resolve时，新对象状态变为fulfilled，所有对象的resolve的value依次添加组成一个新的数组，并以新的数组作为新对象resolve的value，例：

    Promise.all([Promise.resolve(5), 
    Promise.resolve(6), 
    Promise.resolve(7)]).then(function(value){
        console.log('fulfill', value)  // fulfill [5, 6, 7]
    }, function(reason){
        console.log('reject',reason)
    })

当数组中有一个对象reject时，新对象状态变为rejected，并以当前对象reject的reason作为新对象reject的reason。

    Promise.all([Promise.resolve(5), 
    Promise.reject(new Error('error')), 
    Promise.resolve(7),
    Promise.reject(new Error('other error'))
    ]).then(function(value){
        console.log('fulfill', value)
    }, function(reason){
        console.log('reject', reason)  // reject Error: error(…)
    })

那当数组中，传入了非promise对象会如何呢？

    Promise.all([Promise.resolve(5), 
    6,
    true,
    'test',
    undefined,
    null,
    {a:1},
    function(){},
    Promise.resolve(7)
    ]).then(function(value){
        console.log('fulfill', value)  // fulfill [5, 6, true, "test", undefined, null, Object, function, 7]
    }, function(reason){
        console.log('reject', reason)
    })

我们发现，当传入的值为数字、boolean、字符串、undefined、null、{a:1}、function(){}等非promise对象时，会依次把它们添加到新对象resolve时传递的数组中。

那数组中的多个对象是同时调用，还是一个接一个的依次调用呢？我们再看个例子

    function timeout(time) {
        return new Promise(function (resolve) {
            setTimeout(function () {
                resolve(time);
            }, time);
        });
    }
    console.time('promise')
    Promise.all([
        timeout(10),
        timeout(60),
        timeout(100)
    ]).then(function (values) {
        console.log(values); //[10, 60, 100]
        console.timeEnd('promise');   // 107ms 
    });

由此我们可以看出，传入的多个对象几乎是同时执行的，因为总的时间略大于用时最长的一个对象resolve的时间。

- Promise.race() 它同样接收一个promise对象组成的数组作为参数，并返回一个新的promise对象。

与Promise.all()不同，它是在数组中有一个对象（最早改变状态）resolve或reject时，就改变自身的状态，并执行响应的回调。

### Promise 构造函数

    var promise = new Promise(function (resolve, reject) {
        // ...

        if (/* 异步操作成功 */){
            resolve(value);
        } else { /* 异步操作失败 */
            reject(new Error());
        }
    });

Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数，由 JavaScript 引擎提供，不用自己实现。

resolve函数的作用是，将Promise实例的状态从“未完成”变为“成功”（即从pending变为fulfilled），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去。reject函数的作用是，将Promise实例的状态从“未完成”变为“失败”（即从pending变为rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

    function timeout(ms) {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, ms, 'done');
    });
    }

    timeout(100)

上面代码中，timeout(100)返回一个 Promise 实例。100毫秒以后，该实例的状态会变为fulfilled。

- Promise 新建后就会立即执行。

    let promise = new Promise(function(resolve, reject) {
    console.log('Promise');
    resolve();
    });

    promise.then(function() {
    console.log('resolved.');
    });

    console.log('Hi!');

    // Promise
    // Hi!
    // resolved

上面代码中，Promise 新建后立即执行，所以首先输出的是Promise。然后，then方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行，所以resolved最后输出。

### Promise.prototype.then()

Promise 实例的then方法，用来添加回调函数。

then方法可以接受两个回调函数，第一个是异步操作成功时（变为fulfilled状态）时的回调函数，第二个是异步操作失败（变为rejected）时的回调函数（该参数可以省略）。一旦状态改变，就调用相应的回调函数。

    var p1 = new Promise(function (resolve, reject) {
    resolve('成功');
    });
    p1.then(console.log, console.error);
    // "成功"

    var p2 = new Promise(function (resolve, reject) {
    reject(new Error('失败'));
    });
    p2.then(console.log, console.error);
    // Error: 失败

    p1
    .then(step1)
    .then(step2)
    .then(step3)
    .then(
        console.log,
        console.error
    );
    
上面代码中，p1后面有四个then，意味依次有四个回调函数。只要前一步的状态变为fulfilled，就会依次执行紧跟在后面的回调函数。

最后一个then方法，回调函数是console.log和console.error，用法上有一点重要的区别。console.log只显示step3的返回值，而console.error可以显示p1、step1、step2、step3之中任意一个发生的错误。举例来说，如果step1的状态变为rejected，那么step2和step3都不会执行了（因为它们是resolved的回调函数）。Promise 开始寻找，接下来第一个为rejected的回调函数，在上面代码中是console.error。这就是说，Promise 对象的报错具有传递性。

### Promise.prototype.finally()
finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。

    promise
    .then(result => {···})
    .catch(error => {···})
    .finally(() => {···});

上面代码中，不管promise最后的状态，在执行完then或catch指定的回调函数以后，都会执行finally方法指定的回调函数。

### then() 用法辨析

Promise 的用法，简单说就是一句话：使用then方法添加回调函数。但是，不同的写法有一些细微的差别，请看下面四种写法，它们的差别在哪里？

    // 写法一
    f1().then(function () {
    return f2();
    });

    // 写法二
    f1().then(function () {
    f2();
    });

    // 写法三
    f1().then(f2());

    // 写法四
    f1().then(f2);

为了便于讲解，下面这四种写法都再用then方法接一个回调函数f3。

写法一的f3回调函数的参数，是f2函数的运行结果。

    f1().then(function () {
    return f2();
    }).then(f3);

写法二的f3回调函数的参数是undefined。

    f1().then(function () {
    f2();
    return;
    }).then(f3);

写法三的f3回调函数的参数，是f2函数返回的函数的运行结果。

    f1().then(f2())
    .then(f3);

写法四与写法一只有一个差别，那就是f2会接收到f1()返回的结果。

    f1().then(f2)
    .then(f3);

### Promise 的实例

1. 加载图片

我们可以把图片的加载写成一个Promise对象。

    ```js
    var preloadImage = function (path) {
        return new Promise(function (resolve, reject) {
            var image = new Image();
            image.onload  = resolve;
            image.onerror = reject;
            image.src = path;
        });
    };
    ```
    ```js
    //或
    function loadImageAsync(url) {
        return new promise(function(resolve, reject) {
            const image = new Image();
            image.onload = function() {
                resolve(image);
            }
            image.onerror = function() {
                reject(image);
            };
            image.src = url;
        })
    }
    ```

2. Ajax 操作

Ajax 操作是典型的异步操作，传统上往往写成下面这样。

    ```js
    function search(term, onload, onerror) {
    var xhr, results, url;
    url = 'http://example.com/search?q=' + term;

    xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);

    xhr.onload = function (e) {
        if (this.status === 200) {
        results = JSON.parse(this.responseText);
        onload(results);
        }
    };
    xhr.onerror = function (e) {
        onerror(e);
    };

    xhr.send();
    }

    search('Hello World', console.log, console.error);
    ```

如果使用 Promise 对象，就可以写成下面这样。

    ```js
    function search(term) {
    var url = 'http://example.com/search?q=' + term;
    var xhr = new XMLHttpRequest();
    var result;

    var p = new Promise(function (resolve, reject) {
        xhr.open('GET', url, true);
        xhr.onload = function (e) {
        if (this.status === 200) {
            result = JSON.parse(this.responseText);
            resolve(result);
        }
        };
        xhr.onerror = function (e) {
        reject(e);
        };
        xhr.send();
    });

    return p;
    }

    search('Hello World').then(console.log, console.error);
    ```
    ```js
    //或
    function getJSON(url) {
        const promise = new Promise(function(resolve, reject) {
            const handler = function() {
                if(this.readyState !== 4) {
                    return;
                };
                if(this.status === 200) {
                    resolve(this.response);
                } else {
                    reject(new Error(this.statusText));
                };
            };
            const client = new XMLHttpRequest();
            client.open('GET', url);
            client.onreadystatechange = handler;
            client.responseType = 'json';
            client.setRequestHeader("Accept", "application/json");
            client.send();
        });
        return promise;
    };

    getJSON("/posts.json").then(function(json){
        //
    }).cache(function(e) {
        console.error(error);
    })
    ```

加载图片的例子，也可以用 Ajax 操作完成。

    ```js
    function imgLoad(url) {
        return new Promise(function (resolve, reject) {
            var request = new XMLHttpRequest();
            request.open('GET', url);
            request.responseType = 'blob';
            request.onload = function () {
                if (request.status === 200) {
                    resolve(request.response);
                } else {
                    reject(new Error('图片加载失败：' + request.statusText));
                }
            };
            request.onerror = function () {
            reject(new Error('发生网络错误'));
            };
            request.send();
        });
    }
    ```

###b 微任务

Promise 的回调函数属于异步任务，会在同步任务之后执行。

    new Promise(function (resolve, reject) {
    resolve(1);
    }).then(console.log);

    console.log(2);
    // 2
    // 1

上面代码会先输出2，再输出1。因为console.log(2)是同步任务，而then的回调函数属于异步任务，一定晚于同步任务执行。

**但是，Promise 的回调函数不是正常的异步任务，而是微任务（microtask）。它们的区别在于，正常任务追加到下一轮事件循环，微任务追加到本轮事件循环。这意味着，微任务的执行时间一定早于正常任务。**

    setTimeout(function() {
    console.log(1);
    }, 0);

    new Promise(function (resolve, reject) {
    resolve(2);
    }).then(console.log);

    console.log(3);
    // 3
    // 2
    // 1

上面代码的输出结果是321。这说明then的回调函数的执行时间，早于setTimeout(fn, 0)。因为then是本轮事件循环执行，setTimeout(fn, 0)在下一轮事件循环开始时执行。

### 兼容

新版的chrome和firefox也已经支持。但是低版本的浏览器我们可以使用`es6-promise`这个polyfill库来加以兼容。

### 小结

Promise 的优点在于，让回调函数变成了规范的链式写法，程序流程可以看得很清楚。它有一整套接口，可以实现许多强大的功能，比如同时执行多个异步操作，等到它们的状态都改变以后，再执行一个回调函数；再比如，为多个回调函数中抛出的错误，统一指定处理方法等等。

而且，Promise 还有一个传统写法没有的好处：它的状态一旦改变，无论何时查询，都能得到这个状态。这意味着，无论何时为 Promise 实例添加回调函数，该函数都能正确执行。所以，你不用担心是否错过了某个事件或信号。如果是传统写法，通过监听事件来执行回调函数，一旦错过了事件，再添加回调函数是不会执行的。

Promise也有一些缺点。首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。第三，当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

如果某些事件不断地反复发生，一般来说，使用 Stream 模式是比部署Promise更好的选择。

[origin](http://javascript.ruanyifeng.com/advanced/promise.html)

[origin](https://segmentfault.com/a/1190000007678185)

